name: location_marker_example
description: Example of FlutterMapLocationMarkerPlugin
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_joystick: ^0.2.1
  flutter_map: ^8.0.0
  flutter_map_location_marker_plus:
    path: ../
  geolocator: ^13.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: any

flutter:
  uses-material-design: true
